name: Build
on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
    - uses: actions/setup-node@v1
      with:
        node-version: 12.x
    - name: install
      run: |
        npm i -g typescript
        npm i -g pkg
        npm install
    - name: pkg
      run: |
        npm run compile
        npm run pkg
    - name: artifact
      uses: actions/upload-artifact@master
      with:
        name: binaries
        path: binaries
    - name: release
      uses: softprops/action-gh-release@v1
      if: startsWith(github.ref, 'refs/tags/')
      with:
        files: binaries/*
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
